{
 "title": "sharing",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Status code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(code) (http_request_duration_seconds_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_runtime_cpu_usage ", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "current connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_server_kestrel_current_connections",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}