name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Install Coverlet tool
      run: dotnet tool install --global coverlet.console

    - name: Install SonarScanner tool
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Sonar Scanner Begin
      run: dotnet sonarscanner begin /k:"Antik88_ShortSharing" /d:sonar.organization="antik88" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.opencover.reportsPaths="coverage.opencover.xml"

    - name: Run Tests with Coverlet
      run: coverlet ./ShortSharing.Tests/bin/Release/net7.0/ShortSharing.Tests.dll --target "dotnet" --targetargs "test --no-build --configuration Release" -f opencover -o "coverage.opencover.xml"

    - name: Sonar Scanner End
      run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: TestResults
        path: ./TestResults/*.trx

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: CoverageReport
        path: ./coverage.opencover.xml
